/**
 * NEXUS Gemini Sync
 *
 * Synchronize Architect.md Gemini settings to .gemini/settings.json
 * and generate GEMINI.md for Gemini CLI context awareness.
 *
 * @module nexus/sync/gemini-sync
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { loadConfig } = require('../core/config-parser');
const { getEventBus } = require('../core/event-bus');

const ROOT = path.resolve(__dirname, '..', '..');
const GEMINI_DIR = path.join(ROOT, '.gemini');
const GEMINI_SETTINGS = path.join(GEMINI_DIR, 'settings.json');
const GEMINI_MD = path.join(ROOT, 'GEMINI.md');

class GeminiSync {
  constructor() {
    this.bus = getEventBus();
  }

  /**
   * Sync Architect.md settings to Gemini CLI config
   */
  sync() {
    const config = loadConfig();
    if (!config || !config.providers) return { synced: false, reason: 'no_config' };

    const gemini = config.providers['gemini-cli'];
    if (!gemini) return { synced: false, reason: 'no_gemini_provider' };

    const results = {
      settings: this._syncSettings(config),
      geminiMd: this._syncGeminiMd(config)
    };

    this.bus.emit('sync:gemini', results);
    return { synced: true, ...results };
  }

  /**
   * Sync .gemini/settings.json
   */
  _syncSettings(config) {
    if (!fs.existsSync(GEMINI_DIR)) {
      fs.mkdirSync(GEMINI_DIR, { recursive: true });
    }

    let existing = {};
    try {
      if (fs.existsSync(GEMINI_SETTINGS)) {
        existing = JSON.parse(fs.readFileSync(GEMINI_SETTINGS, 'utf8'));
      }
    } catch (e) {}

    // Merge NEXUS context into Gemini settings
    const updated = {
      ...existing,
      nexus: {
        enabled: true,
        role: config.providers['gemini-cli']?.role || 'collaborator',
        strengths: config.providers['gemini-cli']?.strengths || [],
        lastSync: new Date().toISOString()
      }
    };

    fs.writeFileSync(GEMINI_SETTINGS, JSON.stringify(updated, null, 2));
    return { path: GEMINI_SETTINGS, status: 'updated' };
  }

  /**
   * Generate GEMINI.md for Gemini CLI context
   */
  _syncGeminiMd(config) {
    const gemini = config.providers['gemini-cli'] || {};
    const claude = config.providers['claude-code'] || {};
    const codex = config.providers['codex-cli'] || {};

    const workflows = Array.isArray(config.workflows) ? config.workflows : Object.values(config.workflows || {});
    const routing = Array.isArray(config.routingRules) ? config.routingRules : Object.values(config.routingRules || {});

    const lines = [
      '# GEMINI.md - NEXUS Context for Gemini CLI',
      '',
      '> Auto-generated by NEXUS sync. Do not edit manually.',
      `> Last sync: ${new Date().toISOString()}`,
      '',
      '---',
      '',
      '## Your Role in NEXUS',
      '',
      `- **Role**: ${gemini.role || 'collaborator'}`,
      `- **Strengths**: ${(gemini.strengths || []).join(', ')}`,
      `- **Context Window**: ${gemini.context || '1M'}`,
      `- **Cost Tier**: ${gemini.costTier || 'free'}`,
      '',
      '## Other Providers',
      '',
      `- **Claude Code** (${claude.role || 'primary'}): ${(claude.strengths || []).join(', ')}`,
      `- **Codex CLI** (${codex.role || 'specialist'}): ${(codex.strengths || []).join(', ')}`,
      '',
      '## Routing Rules (tasks routed to you)',
      ''
    ];

    // Show routing rules relevant to Gemini
    for (const rule of routing) {
      if (rule.provider === 'gemini-cli' || (rule.fallbacks && rule.fallbacks.includes('gemini-cli'))) {
        lines.push(`- **${rule.taskType}**: ${rule.provider === 'gemini-cli' ? 'Primary' : 'Fallback'}`);
      }
    }

    lines.push('');
    lines.push('## Workflows You Participate In');
    lines.push('');

    for (const wf of workflows) {
      lines.push(`- **${wf.id}**: ${wf.name} (triggers: ${(wf.triggers || []).join(', ')})`);
    }

    lines.push('');
    lines.push('## Coordination Protocol');
    lines.push('');
    lines.push('When working on NEXUS tasks:');
    lines.push('1. Check task type and confirm your role (primary/fallback)');
    lines.push('2. Follow the workflow template steps');
    lines.push('3. Report results in structured JSON format');
    lines.push('4. Flag any issues for Claude Code to review');
    lines.push('');
    lines.push('## Project Root');
    lines.push('');
    lines.push(`- **Path**: ${ROOT.replace(/\\/g, '/')}`);
    lines.push('- **Config**: nexus/Architect.md');
    lines.push('');
    lines.push('---');
    lines.push('*Generated by NEXUS v1.0.0*');
    lines.push('');

    fs.writeFileSync(GEMINI_MD, lines.join('\n'));
    return { path: GEMINI_MD, status: 'generated' };
  }
}

module.exports = { GeminiSync };

// CLI
if (require.main === module) {
  const sync = new GeminiSync();
  const result = sync.sync();
  if (result.synced) {
    console.log('[+] Gemini sync complete');
    console.log(`    Settings: ${result.settings.path}`);
    console.log(`    GEMINI.md: ${result.geminiMd.path}`);
  } else {
    console.log(`[-] Sync skipped: ${result.reason}`);
  }
}
